name: CI/CD Pipeline FIAP API


on:
  push:
    branches:
      - main


jobs:
    build:
        runs-on: ubuntu-latest


        steps:
          - name: Chekout Repository
            uses: actions/checkout@v2

          - name: Login to Docker hub
            run: echo ${{ secrets.DOCKERHUB_PASSWORD_NEW }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME_NEW }} --password-stdin



          - name: Build and Push Docker Image
            run:
              docker build -t kaiqueleoanardo12/fiapapidocker:latest .


          - name: Publish image
            run:
              docker push kaiqueleoanardo12/fiapapidocker:latest

          - name: Listar arquivos no diretorio
            run:
              echo "Executando dir"
              dir

          - name: Deploy to AKS
            run:
              kubectl apply -f FiapApiDocker/YAMLS/deployment.yaml

          - name: Waiting deploy to AKS
            run:
              kubectl wait --for=condition=available deployment/fiapapipod
