name: CI/CD Pipeline FIAP API


on:
  push:
    branches:
      - main


jobs:
    build:
        runs-on: ubuntu-latest


        steps:
          - name: Chekout Repository
            uses: actions/checkout@v2

          - name: Login to Docker hub
            run: echo ${{ secrets.DOCKERHUB_PASSWORD }} | docker login -u ${{ secrets.DOCKERHUB_USERNAME }} --password-stdin



          - name: Build and Push Docker Image
            run:
              docker build -t kaiqueleoanardo12/fiapapidocker:latest .
              docker push kaiqueleoanardo12/fiapapidocker:latest


          - name: Set up kubectl
            uses: azure/k8s-set-context@v1
            with:
              method: kubeconfig
              kubeconfig: ${{ secrets.KUBE_CONFIG_NEW }}
              version: 1.21.0

          
          - name: Deploy to AKS
            run:
              kubectl apply -f deployment.yaml
